branch-defaults:
  master:
    environment: apieventx-dev
environment-defaults:
  apieventx-dev:
    branch: null
    repository: null
global:
  application_name: api.eventx
  default_ec2_keyname: null
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
deploy:
  artifact: dist/server.zip
