version: 2
jobs:
    server:
        docker:
            - image: circleci/node:8.8.1
        steps:
            - checkout
            - restore_cache:
                keys:
                    - cache-server-{{ checksum "package.json" }}
            - run:
                name: Install NPM packages
                command: npm install
            - save_cache:
                key: cache-server-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: build
                command: npm run build
            - run:
                name: Prepare ZIP file
                command: zip dist/server.zip package.json && cd dist && zip server.zip -r * -x server.zip
            - run:
                name: Install AWS and AWS EB CLI tools
                command: sudo apt-get -y install python3-pip && sudo pip3 install --upgrade awscli awsebcli
            - run:
                name: Deploy Server
                command: eb deploy --profile default

workflows:
  version: 2
  build-deploy:
    jobs:
      - server